import { test, expect } from '@playwright/test'

test('initial password gate, real node operation, navigation and mobile layout', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/nodes')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('用户名', { exact: true }).fill('admin')
  await page.getByLabel('密码', { exact: true }).fill('Initial-e2e-password-2026')
  await page.getByRole('button', { name: '进入控制台' }).click()
  await expect(page).toHaveURL(/\/change-password$/)
  await page.goto('/nodes')
  await expect(page).toHaveURL(/\/change-password$/)
  await expect(page.getByRole('heading', { name: '设置你的专属密码' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('first-login-desktop.png'), fullPage: true })
  await page.getByLabel('初始 / 当前密码').fill('Initial-e2e-password-2026')
  await page.getByLabel('新密码', { exact: true }).fill('Changed-e2e-password-2026')
  await page.getByLabel('确认新密码').fill('Mismatch-password-2026')
  await page.getByRole('button', { name: '修改密码并进入面板' }).click()
  await expect(page.getByRole('alert')).toContainText('两次输入的新密码不一致')
  await page.getByLabel('确认新密码').fill('Changed-e2e-password-2026')
  await page.getByRole('button', { name: '修改密码并进入面板' }).click()
  await expect(page.getByRole('heading', { name: '运行概览' })).toBeVisible()
  await expect(page.getByText('Browser test node', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '管理 Browser test node' }).click()
  await expect(page.getByRole('dialog', { name: 'Browser test node' })).toBeVisible()
  await page.getByRole('button', { name: '系统快照', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '系统快照' })).toBeVisible()
  await expect(page.getByRole('dialog').getByText('已完成', { exact: true })).toBeVisible({ timeout: 30000 })
  await expect(page.getByRole('dialog').locator('pre')).toContainText('disk_used_percent')
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await page.getByRole('link', { name: /^节点管理/ }).click()
  await page.getByLabel('搜索节点').fill('no matching node')
  await expect(page.getByRole('heading', { name: '没有匹配的节点' })).toBeVisible()
  await page.getByLabel('搜索节点').fill('')
  await page.getByRole('button', { name: '管理 Browser test node' }).click()
  await page.getByRole('dialog', { name: 'Browser test node' }).getByLabel('节点名称', { exact: true }).fill('Updated browser node')
  await page.getByRole('dialog', { name: 'Browser test node' }).getByLabel('分组', { exact: true }).fill('Browser QA')
  await page.getByRole('button', { name: '保存节点策略' }).click()
  await expect(page.getByRole('status')).toContainText('策略已保存')
  await page.getByRole('button', { name: '关闭窗口' }).click()
  await expect(page.getByText('Updated browser node', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '接入节点', exact: true }).click()
  await page.getByRole('dialog', { name: '接入新节点' }).getByLabel('节点名称', { exact: true }).fill('New test enrollment')
  await page.getByRole('button', { name: '生成接入令牌' }).click()
  await expect(page.getByTestId('enrollment-token')).toHaveText(/.{20,}/)
  await expect(page.getByRole('dialog').locator('pre')).toContainText('http://127.0.0.1:19090')
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await page.getByRole('link', { name: '运行概览', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('dashboard-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { name: '运行概览' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('dashboard-mobile.png'), fullPage: true })
  await page.getByRole('link', { name: /^节点管理/ }).click()
  await page.getByRole('button', { name: '管理 Updated browser node' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.getByRole('dialog').evaluate(el => el.getBoundingClientRect().width <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('node-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: '关闭窗口' }).click()
  await page.getByRole('button', { name: '退出登录' }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('密码', { exact: true }).fill('Initial-e2e-password-2026')
  await page.getByRole('button', { name: '进入控制台' }).click()
  await expect(page.getByRole('alert')).toContainText('用户名或密码不正确')
  await page.getByLabel('密码', { exact: true }).fill('Changed-e2e-password-2026')
  await page.getByRole('button', { name: '进入控制台' }).click()
  await expect(page.getByRole('heading', { name: '运行概览' })).toBeVisible()
  expect(errors).toEqual([])
})
